<?php 
ob_start ();
session_start();
define("host_name", "localhost");
define("user_name", "root");
define("db_name", "it16a1");
define("db_password", "");
define("ftp_server", "192.168.1.8");
define("ftp_username", "hunghi");
define("ftp_password", "hung12b3");
define("domain", "http://cmspage.vn");
define("pubdomain", "http://pub.vn");
define("limit", "5");
define("limit2", "10");
define("limit3", "20");
define("status_1", "New");
define("status_2", "Public");
define("status_3", "Update");
define("status_4", "Unpublic");
define("status_5", "WaitingAR1");
define("status_6", "WaitingAR2");
define("status_7", "WaitingAR3");
define("status_8", "WaitingMT");
define("status_9", "Denail");
define("isrollback","on");
define("isshare","on");
define("app_id","1203696650022894");
define("CATEGORY_1","Thể thao");
define("CATEGORY_2","Văn hóa");
define("CATEGORY_3","Giải trí");
define("AUTO_LINK","<!-- auto link -->");
?>